# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.questaInstallPath C:/questasim64_10.6c/win64
create_project -in_memory -part xcku060-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Simone Ragoni/alice/CtpReadout/ctp_readout2/ctp_readout2.srcs/sources_1/new/buffer_fifo.vhd}
  {C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/new/ir_statemachine.vhd}
  {C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/new/packer_ir2.vhd}
  {C:/Users/Simone Ragoni/alice/WholeCTPfromGitLab/common_logic/RTL/Trigger_class_record/prsg_tcr.vhd}
  {C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/new/top_ir_statemachine.vhd}
}
read_ip -quiet {{C:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_ir_statemachine -part xcku060-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_ir_statemachine.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_ir_statemachine_utilization_synth.rpt -pb top_ir_statemachine_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
