######################################################################
#
# File name : IR_tb_wave.do
# Created on: Tue Nov 02 16:11:47 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
