######################################################################
#
# File name : IR_tb.udo
# Created on: Tue Nov 02 16:11:47 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
