######################################################################
#
# File name : IR_tb_simulate.do
# Created on: Mon Dec 13 14:15:02 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib IR_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {IR_tb_wave.do}

view wave
view structure
view signals

do {IR_tb.udo}

run 1000ns
