# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xci
# IP: The module: 'ir_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ir_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ir_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xci
# IP: The module: 'ir_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ir_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Simone Ragoni/alice/InteractionRecord/IR/IR.srcs/sources_1/ip/ir_fifo/ir_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ir_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
